name: CB
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pytorch==1.12.1
  - python==3.10.9
  - pandas==1.5.3
  - conda-forge::pygrib=2.1.4
  - numpy==1.23.5
  - cartopy==0.21.1
  - tensorboard==2.12.0
  - pip:
      - ecmwf-opendata==0.1.2
      - matplotlib==3.7.1
      - sondehub==0.3.1